Fix three Hunter spells
AshamaneProject/AshamaneCore pull request #110
Opened 2018-09-08 05:50 UTC by HannibalRoG

Fix three Hunter spells

**Changes proposed:**

-Bursting shoot
-Sentinel
-True aim

**Issues addressed:** Closes #  (insert issue tracker number)

Closes https://bt.ashamane.com/view.php?id=560 and https://bt.ashamane.com/view.php?id=554

**Tests performed:** (Does it build, tested in-game, etc.)
Compiled and tested

**Known issues and TODO list:** (add/remove lines as needed)

- [ ] 
- [ ]

2018-09-08 11:39 UTC, Traesh requested changes

2018-09-08 11:39 UTC, Traesh commented on src/server/scripts/Spells/spell_hunter.cpp
>      }
You should revert this, we use SpellPowerCost& powerCost now

2018-09-08 11:39 UTC, Traesh commented on src/server/scripts/Spells/spell_hunter.cpp
> +        AURA_SHOTING = 224729
You should put this spell in the top-file enum in format SPELL_HUNTER_AURA_SHOOTING

2018-09-08 11:39 UTC, Traesh commented on src/server/scripts/Spells/spell_hunter.cpp
> +	RegisterAreaTriggerAI(at_hun_sentinel);
Use 4 spaces rather than tab :)

2018-09-08 11:39 UTC, Traesh commented on sql/ashamane/world/2018_09_08_00_world_spell_areatrigger.sql
> +INSERT INTO `spell_areatrigger` (`SpellMiscId`, `AreaTriggerId`, `MoveCurveId`, `ScaleCurveId`, `MorphCurveId`, `FacingCurveId`, `DecalPropertiesId`, `TimeToTarget`, `TimeToTargetScale`, `VerifiedBui
Is this sniffed data ? If yes you should set VerifiedBuild to a valid value, if not set it to 0 (same for areatrigger_template)

2018-09-08 18:43 UTC, Traesh commented
Why did you remove all my modifications ? xD

2018-09-08 20:10 UTC, HannibalRoG commented
Sorry, i dont see it, take care of that.

2018-09-13 12:40 UTC, anubislinux commented
Of course he does not know, because I get it from the filtered source and since he does not know about programming or c ++ ... Nothing lucky with the development staff

2018-09-18 05:06 UTC, HannibalRoG commented
Hey @Traesh can you merge this?

2018-09-21 09:19 UTC, Traesh approved these changes

2018-09-21 09:32 UTC, merged